export interface ErrorResponse {
  errorCode: string;
  message: string;
}

export enum ErrorCode {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  COURSE_DOES_NOT_EXIST = 'COURSE_DOES_NOT_EXIST',
  COURSE_NOT_UPDATED = 'COURSE_NOT_UPDATED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  ALREADY_DELETED = 'ALREADY_DELETED',
  DOCUMENTS_NOT_ADDED = 'DOCUMENTS_NOT_ADDED',
  NO_DOCUMENTS_PROVIDED = 'NO_DOCUMENTS_PROVIDED',
  ASSIGNMENT_STATUS_NOT_UPDATED = 'ASSIGNMENT_STATUS_NOT_UPDATED',
  ASSIGNMENT_STATUS_NOT_VALID = 'ASSIGNMENT_STATUS_NOT_VALID',
  GROUP_SESSIONS_NOT_UPDATED = 'GROUP_SESSIONS_NOT_UPDATED',
  GROUP_NOT_CREATED = 'GROUP_NOT_CREATED',
  USER_NOT_UPDATED = 'USER_NOT_UPDATED',
  GROUP_FETCH_FAILED = 'GROUP_FETCH_FAILED',
  GROUP_UPDATE_FAILED = 'GROUP_UPDATE_FAILED',
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  ASSIGNMENT_ALREADY_IN_PROGRESS = 'ASSIGNMENT_ALREADY_IN_PROGRESS',
  NO_AVAILABLE_SLOTS_FOR_ON_DEMAND_SESSIONS = 'NO_AVAILABLE_SLOTS_FOR_ON_DEMAND_SESSIONS'
}

