name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Check PR Checks workflow status
        uses: actions/github-script@v7
        id: check-workflow
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.pull_request?.head.ref || context.ref;
            
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'pr-checks.yml',
              branch,
              status: 'completed'
            });
            
            const latestRun = workflows.data.workflow_runs[0];
            return latestRun?.conclusion === 'success';

      - name: Auto-merge PR
        if: steps.check-workflow.outputs.result == 'true'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: "automerge"
          UPDATE_METHOD: "rebase" 