name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            
            // Don't delete protected branches
            const protectedBranches = ['main', 'develop', 'staging'];
            if (protectedBranches.includes(branch)) {
              console.log(`Branch ${branch} is protected and won't be deleted`);
              return;
            }
            
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch}`
              });
              console.log(`Branch ${branch} deleted successfully`);
            } catch (error) {
              console.log(`Error deleting branch ${branch}: ${error}`);
            } 