name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["Create Issue from PR", "Pull Request Links"]
    types: [completed]

jobs:
  check-workflows:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'failure'
    steps:
      - uses: actions/checkout@v4

      - name: Check all workflow runs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            
            // Get all workflow runs for this PR
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              branch: pr ? pr.head.ref : context.ref,
              status: 'completed'
            });
            
            // Check if any workflow failed
            const hasFailures = runs.data.workflow_runs.some(run => run.conclusion === 'failure');
            
            if (!hasFailures) {
              // Add automerge label if all checks passed
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: pr.number,
                labels: ['automerge']
              });
              
              console.log('All checks passed, added automerge label');
            } else {
              // Remove automerge label if any check failed
              try {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: pr.number,
                  name: 'automerge'
                });
              } catch (error) {
                // Label might not exist, ignore error
                console.log('No automerge label to remove');
              }
              
              console.log('Some checks failed, removed automerge label');
            }