name: Pull Request Links

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr-links:
    runs-on: ubuntu-latest
    if: ${{ contains(github.head_ref, 'issue-') && !contains(github.event.pull_request.labels.*.name, 'from-pr') }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Link Pull Request to Issue
        uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: ${{ secrets.PAT }}
          branch-prefix: 'issue-'
          resolve: 'true'